on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2025, macos-15, ubuntu-24.04]
        include:
          - os: windows-2025
          - os: macos-15
          - os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
        if: ${{ matrix.os == 'windows-2025' }}
        name: setup msvc vcvars
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.10"
      - name: Install libc++ on Ubuntu
        run: sudo apt-get update && sudo apt-get install -y libc++-dev libc++abi-dev
        if: ${{ matrix.os == 'ubuntu-24.04' }}
      - name: Install autotools on macOS
        run: brew install automake libtool
        if: ${{ matrix.os == 'macos-15' }}
      - name: Install Conan
        run: pip install conan pytest && conan --version
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.31.7"
          ninjaVersion: "^1.11.1"
      - name: Run Tests
        run: pytest -rA -v
  example:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"
      - name: Install Conan
        run: pip install conan && conan --version
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.31.7"
          ninjaVersion: "^1.11.1"
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=../conan_provider.cmake -DCMAKE_BUILD_TYPE=Release
        working-directory: example
      - name: Build example
        run: cmake --build build
        working-directory: example
      - name: Run example
        run: build/main
        working-directory: example
